[project]
name = "modelling-ai-usage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "mesa>=3.1.5",
    "networkx>=3.4.2",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pip>=25.0.1",
    "seaborn>=0.13.2",
    "sns>=0.1",
    "solara>=1.44.1",
]
